# Site settings
title: Projeto Carambolo!
description: Um projeto pela vida!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Projeto Carambolo!
user_description: Um projeto pela vida!
user_title: Um projeto pela vida!
email: projetocarambolo@gmail.com
facebook_username: projetocarambolo
instagram_username: projetocarambolo
twitter_username: projetocarambolo
github_username:  teresinahc
gplus_username:  projetocarambolo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
