permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: null
markdown: kramdown
extensions: [fenced_code_blocks]
excerpt_separator: "<!--more-->"
url:
baseurl: ""

data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

post_limit: 5


title : Projeto Carambolo, o ano inteiro amarelo!
tagline: vida, setembro, amarelo, psicologia, teresina, hacker, code
author :
  name : Teresina Hacker Clube
  site: https://teresinahc.github.io/
  description : Um projeto criado para salvar vidas!
  image : social-image.png
  email :
  github : teresinahc
  twitter :
  facebook:
  linkedin:
  instagram:

twitter_username:
production_url :

JB :
  version : 0.3.0
  BASE_PATH :


  ASSET_PATH :

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : jeky-new-age
      num_posts: 5
      width: 580
      colorscheme: light

  analytics :
    provider : google
    google :
        tracking_id : 'UA-94080000-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik'
        idsite : '1'

  sharing :
    provider : false
